; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26732.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Onur\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
